# Generated by Django 6.0.6 on 2026-06-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodalCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('company_name', models.CharField(default='', max_length=300)),
                ('reports_json', models.TextField(default='[]')),
                ('total_raw', models.IntegerField(default=0)),
                ('total_final', models.IntegerField(default=0)),
                ('crawl_method', models.CharField(default='', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'codal_cache',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='ProxyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_url', models.URLField(unique=True)),
                ('label', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('test_ok', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'proxy_config',
            },
        ),
    ]
